# Generated by Django 5.1.5 on 2025-02-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_orders_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
