# Generated by Django 5.1.5 on 2025-02-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_orders_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
