# Generated by Django 5.1.5 on 2025-01-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmsAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
