# Generated by Django 5.1.5 on 2025-02-06 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmsAdmin', '0003_login_groups_login_is_superuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='LOGIN_ID',
            new_name='login',
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theater_name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='theater/')),
                ('contact', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theater', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
