# Generated by Django 5.1.5 on 2025-02-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmsAdmin', '0004_rename_login_id_user_login_theater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cart',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
