# Generated by Django 5.1.5 on 2025-02-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmsAdmin', '0005_alter_user_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=1, upload_to='users/'),
            preserve_default=False,
        ),
    ]
