# Generated by Django 5.1.5 on 2025-02-21 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmsAdmin', '0007_location_alter_theater_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theater',
            name='location',
        ),
    ]
