# Generated by Django 5.1.5 on 2025-02-21 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmsAdmin', '0008_remove_theater_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='theaters', to='bmsAdmin.location'),
            preserve_default=False,
        ),
    ]
